### ISSUE TITLE
Comment replies

### ISSUE THREAD

**Issue by TheNightmanCodeth** [TheNightmanCodeth/DitRa#12]
**Is your feature request related to a problem? Please describe.**
As it stands, the comments view only shows first-level replies. The comment replies need to be displayed beneath their parent comments.

**Describe the solution you'd like**
A child comment should be shrunk a bit to the right.

**Comment by Patte1808** [comment]
Do you already have a solution for it?

I'm currently also working on a Reddit client using Flutter and had to wrap my head around this for quite a long time (longer than I would like to admit :D). If you want, you can use my solution. It's far from perfect at this moment, but it seems to work and just that you get an idea. :) 

```
void _getNestedComments(List replies, List widgets, int level) {
    level++;
    replies.forEach((reply) {
      if (reply is Comment) {
        widgets.add(CommentCard(reply, level));

        if (reply.replies != null) {
          _getNestedComments(reply.replies.comments, widgets, level);
        }
      }
    });
  }
```

And it's being called like that:
```
CommentForest commentForest = submission.comments;

            List<Widget> nestedComments = [];

            _getNestedComments(commentForest.comments, nestedComments, 0);

            return ListView.builder(
              itemCount: nestedComments.length,
              itemBuilder: (context, index) {
                return nestedComments[index];
              },
            );
```

Then I apply the margin on my comment card and multiplying it by the level this comment has.

```
return Card(
      margin: EdgeInsets.only(left: 8.0 * this.level, right: 4.0, bottom: 4.0, top: 4.0),
```

Hope you have a use for it. If you feel like there's something bad in my implementation, I would also be open for feedback, as I'm still learning Flutter and Dart :)

**Comment by TheNightmanCodeth** [comment]
@Patte1808 Thanks a lot!!!! This is how I was thinking I would approach this but I just haven't gotten around to it until now
