### ISSUE TITLE
App is not starting(gradle build failed with flutter run)

### ISSUE THREAD

**Issue by jagdishjadeja** [TheNightmanCodeth/DitRa#7]
Error running Gradle:
Exit code 1 from: PATH\android\gradlew.bat app:properties:
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'PATH\android\app\build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':app'.
> PATH\android\key.properties (The system cannot find the file specified)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

Please review your Gradle project setup in the android/ folder.

I think you need to provide some flutter and android info that you are using.

**Comment by TheNightmanCodeth** [comment]
Yes, sorry I took so long to respond to this, but I'll need to make a debug build version in the app-level gradle file. I actually had this set up on my local machine but forgot to push the changes/:

**Comment by jagdishjadeja** [comment]
so is it solved now ?

**Comment by TheNightmanCodeth** [comment]
@jagdishjadeja Yep. Check out the wiki for instructions on how to get a build going. You'll need to make a secrets.json with oauth credentials from reddit using your own account.
